/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|


 * DO NOT EDIT THIS FILE!!
 *
 *  TO CUSTOMIZE OrganizationBase PLEASE EDIT ../organization.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
import { Country } from '../country';
import { Lessor } from '../lessor';
import { Organization } from '../organization';
import { Partner } from '../partner';

/**
 * This is the model of Organization object
 *
 */
export class OrganizationBase {

    constructor() { }

    public _id: string;
    public active?: Boolean;
    public externalid: string;
    public formalname?: string;
    public liable?: Boolean;
    public searchname?: string;
    public type?: string;
    // Relations country
    public country: Country | string;
    // Relations lessor
    public lessor: Lessor | string;
    // Relations liableparent
    public liableparent: Organization | string;
    // Relations parent
    public parent: Organization | string;
    // Relations partner
    public partner: Partner | string;
    // Relations ultimateparent
    public ultimateparent: Organization | string;
}
